from model_wrappers.model_wrapper import ModelWrapper
from model_wrappers.resnet_wrapper import ResNetWrapper
from model_wrappers.mobile_vit_wrapper import MobileViTWrapper
from model_wrappers.image_model_wrapper import ImageModelWrapper